version: '3.7'

services:
  postgres:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5434:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=services
    volumes:
      - 'services_pg_data:/bitnami/postgresql'

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'services_redis_data:/bitnami/redis/data'

volumes:
  services_pg_data:
  services_redis_data:
